---
abstract: 'simple range objects for smart matching'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Between
name: Between
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Carp: 0
  Data::Dumper: 0
  Exporter: 0
  Scalar::Util: 0
  base: 0
  constant: 0
  overload: 0
  perl: 5.10.0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Between
  homepage: https://metacpan.org/release/Between
  license: http://dev.perl.org/licenses/
version: 0.001
